#!/usr/bin/env python

import sys
import urllib
import urllib2

PORT = 11540  # see ./chex-server

print urllib2.urlopen('http://localhost:%d/' % PORT, urllib.urlencode([
    ('room_id', 1),
    ('message', sys.stdin.read())
    ])).read()
